Add simple instructions
CABLE-LSM/cable_example pull request #1
Opened 2023-12-15 02:28 UTC by ccarouge

This is to add some simple instructions on how to use this as is so we can share more easily with people.

2023-12-17 22:54 UTC, SeanBryan51 requested changes

2023-12-17 22:54 UTC, SeanBryan51 commented on README.md
> +5. Run with payu: `payu run`
```suggestion
5. Run with payu: `payu run`. Note `payu` will need to be installed with CABLE driver (see https://github.com/payu-org/payu/pull/314)
```

2023-12-17 22:54 UTC, SeanBryan51 commented on config.yaml
> -    - /home/189/sb8430/cable/CABLE-AUX/core/biogeophys/def_soil_params.txt
Why are we removing these inputs?

2023-12-18 00:09 UTC, ccarouge commented on config.yaml
> -    - /home/189/sb8430/cable/CABLE-AUX/core/biogeophys/def_soil_params.txt
These are only needed for CABLE v2. And I didn't want to confuse Paul with them when they aren't used for the main CABLE version.

2023-12-18 00:40 UTC, SeanBryan51 commented on config.yaml
> -    - /home/189/sb8430/cable/CABLE-AUX/core/biogeophys/def_soil_params.txt
Ok. Can you remove the entries in the namelist file? I.e. https://github.com/CABLE-LSM/cable_example/blob/51bf603f28bc53288515e81a9404f0d3ac889c91/cable.nml#L8-L9

2023-12-18 00:42 UTC, SeanBryan51 approved these changes
Happy to merge after the namelist file is updated.

2023-12-18 01:19 UTC, merged